name: genai-project

services:
  frontend:
    container_name: nextjs-frontend
    build:
      context: ./genai-project-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - genai-network

  minio:
    image: quay.io/minio/minio:latest
    container_name: genai-minio
    restart: unless-stopped
    ports:
      - "9100:9000"   # API port
      - "9101:9001"   # Console port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: genaiWS25
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

    networks:
      - genai-network

  minio-init:
    image: quay.io/minio/mc:latest
    container_name: genai-minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 admin genaiWS25 &&
      mc mb myminio/basebucket || true
      "
    networks:
      - genai-network
    restart: "no"

  flashcard-generation-worker:
    image: flashcard-generation-genai-worker
    build:
      context: ./genai-project-worker
      dockerfile: Dockerfile-flashcard-generation-worker
    container_name: flashcard-generation-worker
    depends_on:
      minio:
        condition: service_started
        restart: true
#      rabbitmq:
#        condition: service_started
#        restart: true
#      postgres:
#        condition: service_started
#        restart: true
    networks:
      - genai-network

  summary-generation-worker:
    image: summary-generation-genai-worker
    build:
      context: ./genai-project-worker
      dockerfile: Dockerfile-summary-generation-worker
    container_name: summary-generation-worker
    depends_on:
      minio:
        condition: service_started
        restart: true
    #      rabbitmq:
    #        condition: service_started
    #        restart: true
    #      postgres:
    #        condition: service_started
    #        restart: true
    networks:
      - genai-network

  text-extraction-worker:
    image: text-extraction-genai-worker
    build:
      context: ./genai-project-worker
      dockerfile: Dockerfile-text-extraction-worker
    container_name: text-extraction-worker
    depends_on:
      minio:
        condition: service_started
        restart: true
    #      rabbitmq:
    #        condition: service_started
    #        restart: true
    #      postgres:
    #        condition: service_started
    #        restart: true
    networks:
      - genai-network

  aggregation-worker:
    image: aggregation-genai-worker
    build:
      context: ./genai-project-worker
      dockerfile: Dockerfile-aggregation-worker
    container_name: aggregation-worker
    depends_on:
      minio:
        condition: service_started
        restart: true
    #      rabbitmq:
    #        condition: service_started
    #        restart: true
    #      postgres:
    #        condition: service_started
    #        restart: true
    networks:
      - genai-network

  postgres:
    image: postgres:16-alpine
    container_name: genai-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: genai_user
      POSTGRES_PASSWORD: genai_password
      POSTGRES_DB: genai_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - genai-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U genai_user -d genai_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: genai-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # RabbitMQ port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - genai-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: spring-backend
    build:
      context: ./genai-project-backend
      dockerfile: genai-project-backend/backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/genai_db
      - SPRING_DATASOURCE_USERNAME=genai_user
      - SPRING_DATASOURCE_PASSWORD=genai_password
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - genai-network


networks:
  genai-network:
    driver: bridge
